### ISSUE TITLE
Chrome RangError : Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Aarbel** [React-Sight/React-Sight#110] opened 2017-12-19 12:30 UTC
Error just occurs when 
- i installed the extension from chrome store 
- i reloaded my React App 

![image](https://user-images.githubusercontent.com/25119847/34157168-b0a8ea14-e4c0-11e7-9731-5f141dfa8a78.png)

```installHook.js:138 Uncaught RangeError: Maximum call stack size exceeded
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:138:20)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:166:30)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:166:30)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:166:30)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:166:30)
    at props.(anonymous function).forEach (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:161:33)
    at Array.forEach (<anonymous>)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:160:20)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:166:30)
    at props.(anonymous function).forEach (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:161:33)
```

**Comment by Aarbel** [comment] 2017-12-27 19:14
@davidcsally @hewilliam @Grant05 how could we fix it ? :)

**Comment by davidcsally** [comment] 2017-12-28 07:38
Hi Aarbel, my new years resolution is to fix this. The problem is most likely the parseProps function  getting stuck in a circular reference

**Comment by davidcsally** [comment] 2018-01-23 07:58
Hey! hoping that this is fixed in the new code base. A new version (v1.0.6) is being uploaded to the webstore and should be up soon

the fix was hopefully setting a limit on how many times that function can run, so it doesnt get stuck i an infinite loop -> https://github.com/React-Sight/React-Sight/commit/1bfed928a314fd8b1c28aa9aa5f03a4ba6577f05

**Comment by Aarbel** [comment] 2018-01-23 09:00
@davidcsally thanks a lot !

**Comment by davidcsally** [comment] 2020-04-11 21:19
Going to close, if it pops back up feel free to re-open

**Closed as completed by davidcsally** 2020-04-11 21:19 UTC
Labels: bug
